openapi: 3.0.3
info:
  title: Transcation Service
  description: |-
    This is a transcation service server based on the OpenAPI 3.0 specification
  version: 1.0.11
servers:
  - url: https://localhos:8080
tags:
  - name: transcation-service
    description: create the customer account and maintain customer transcation
  - name: account
    description:  Operations about user account
  - name: transcation
    description: Operations about customer transcations, user can perform credit and debit operations
paths:
  /accounts:
    post:
      tags:
        - account
      summary: Create an account
      description: Create an user account using user document id
      operationId: createAccount
      requestBody:
        description: Create an user account
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AccountCreate'
        required: true
      responses:
        '201':
          description: User Created Successfully 
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'          
        '400':
          description: Invalid document id supplied
        '500':
          description: Internal Server Error
  /accounts/{accountId}:
    get:
      tags:
        - account
      summary: Get an account
      description: Get account by id
      operationId: getAccount
      parameters:
        - name: accountId
          in: path
          description: ID of account
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Get Account Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Account'          
        '404':
          description: Account ID not found
        '500':
          description: Internal server error
  /transcations:
    post:
      tags:
        - transcation
      summary: create transcation, credit and debit transcation are supported.
      description: ''
      operationId: createTranscation
      requestBody:
        content:
          application/json:
            schema:
                $ref: '#/components/schemas/CreateTranscation'          
      responses:
        '200':
          description: successful transaction
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Transcation'
        '400':
          description: Invalid request
        '500':
          description: Internal server error
components:
  schemas:
    CreateTranscation:
      type: object
      required:
        - account_id
        - operation_type_id
        - amount
      properties:
        account_id:
          type: string
          example: b498c034-9f3c-4a9e-9908-10a9eae70845
        operation_type_id:
          type: integer
          example: 1
          enum:
            - 1
            - 2
            - 3
            - 4
        amount:
          type: number
          format: double
          example: 134.6
    Transcation:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: b498c034-9f3c-4a9e-9908-10a9eae70845
        account_id:
          type: string
          example: b498c034-9f3c-4a9e-9908-10a9eae70845
        operation_type_id:
          type: integer
          example: 1
          enum:
            - 1
            - 2
            - 3
            - 4
        amount:
          type: number
          format: double
          example: 134.6
    AccountCreate:
      required:
        - docuement_id
      type: object
      properties:
        document_id:
          type: string
          example: aboceper
    Account:
      type: object
      properties:
        id:
          type: string
          format: uuid
          example: b498c034-9f3c-4a9e-9908-10a9eae70845
        document_id:
          type: string
          example: aboceper
  requestBodies:
    AccountCreate:
      description: Create account request object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/AccountCreate'
